Improve Code Quality
python-bale-bot/python-bale-bot pull request #106
Opened 2024-06-24 11:32 UTC by codaliza

تغییرات انجام شده در تاریخ اسفند سال ۱۴۰۳
این تغییرات به کمک PEP های پایتون انجام گرفته است و در ادامه به آن ادامه خواهد شد

2024-06-26 23:15 UTC, kian-ahmadian commented on bale/attachments/_document.py
> +    def from_dict(cls, data: Optional[Dict], bot):
@codaliza 
این خطا به این دلیل ظاهر شده است، که ما در آبجکت `BaleObject` و فانکشنی به همین نام از پارامتر `payload` به جای `data` استفاده کردیم.

2024-06-26 23:20 UTC, kian-ahmadian requested changes
در کلاس `BaleObject` به دلیل وجود پارامتر `payload` به جای `data` در فانکشن `from_dict` هشدارهایی از سوی Codacy ارسال شده است. این هشدار را رفع نمایید

2024-06-26 23:38 UTC, kian-ahmadian approved these changes

2024-06-26 23:57 UTC, codaliza commented
الان دیگه اوکیه؟

2024-06-26 23:57 UTC, kian-ahmadian approved these changes
**تغییرات اولیه پس از ویرایشاتی دیگر تکمیل و تائید شد.**

2024-06-27 00:01 UTC, codaliza commented
هنوز چک `Codacy Static Code Analysis` تایید نکرده برای همین اول اون رو اوکی میکنم بعد تغییراتو اعمال کنید

2024-06-27 00:28 UTC, codaliza commented
الان دیگه اوکیه

2024-06-27 00:30 UTC, merged